## Dockerfile
################################
## BUILD ENVIRONMENT ###########
################################

# Use the official image with .NET SDK (with IIS Express support)
FROM mcr.microsoft.com/dotnet/sdk:latest AS build

WORKDIR /app

# Copy the csproj files and restore dependencies
COPY ["./People.Presentation/People.Presentation.Server/People.Presentation.Server.csproj", "./People.Presentation/People.Presentation.Server/"]
COPY ["./People.Domain/People.Domain.csproj", "./People.Domain/"]
COPY ["./People.Application/People.Application.csproj", "./People.Application/"]
COPY ["./People.Infrastructure/People.Infrastructure.csproj", "./People.Infrastructure/"]

RUN dotnet restore "People.Presentation/People.Presentation.Server/People.Presentation.Server.csproj"

# Copy the rest of the code
COPY . .

# Remove client assets we don't need
RUN rm -Rf /app/People.Presentation/people.presentation.client

# Build the solution
WORKDIR /app/People.Presentation/People.Presentation.Server
RUN dotnet build "People.Presentation.Server.csproj" -c Release

# Publish the app (using the output directory)
RUN dotnet publish "People.Presentation.Server.csproj" -c Release -o /out

# Use the official .NET runtime image to run the application
FROM mcr.microsoft.com/dotnet/aspnet:8.0

# Set the working directory inside the container
WORKDIR /inetpub/wwwroot

# Copy the published files from the build container
COPY --from=build /out .

# Expose the port that the backend app will run on
EXPOSE 5050

# Useful for debugging 
RUN ls -al

# Run the application
ENTRYPOINT ["dotnet", "People.Presentation.Server.dll"]
