# Use Node.js official image to build the app
FROM node:20 AS build

# Set the working directory inside the container
WORKDIR /app

# Copy package.json, package-lock.json (or yarn.lock) and tsconfig
COPY ./People.Presentation/people.presentation.client/package*.json ./
COPY ./People.Presentation/people.presentation.client/tsconfig.json ./
COPY ./People.Presentation/people.presentation.client/tsconfig.*.json ./

# Install packages
RUN npm i

# Copy the rest of the app files
COPY ./People.Presentation/people.presentation.client/ ./

# Expose the port for the React app
EXPOSE 3000

# Set the default command to run the Vite dev server
CMD ["npm", "run", "dev"]
