# Use Node.js official image to build the app
FROM node:20 AS build

# Set the working directory inside the container
WORKDIR /app

# Copy package.json, package-lock.json (or yarn.lock) and tsconfig
COPY ./People.Presentation/people.presentation.client/package*.json ./
COPY ./People.Presentation/people.presentation.client/tsconfig.json ./
COPY ./People.Presentation/people.presentation.client/tsconfig.*.json ./

# Install packages
RUN npm i 

# Copy the rest of the app files
COPY . ./

# Build the React app (this will create a production build by default)
RUN npm run build

# Use a lightweight server to serve the React build
FROM nginx:alpine

# Copy the build output from the build stage to NGINX's public directory
COPY --from=build /app/dist /usr/share/nginx/html

# Expose the port for the React app
EXPOSE 3000

# Run the NGINX server to serve the app
CMD ["nginx", "-g", "daemon off;"]
