services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 5050:80  # Exposing and mapping container port 80 to host port 5050 (IIS Express runs on port 80 inside the container)
      - 5001:443 # Exposes container port 443 (for HTTPS)
    networks:
      - webapp-network
    depends_on:
      - client
    environment:
      - ASPNETCORE_ENVIRONMENT=production
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - DB_CONNECTION_STRING=Server=people-db,1433;Database=people-db;User Id=sa;Password=YourStrong!Passw0rd;Encrypt=False;TrustServerCertificate=True;  # DB connection string
      - REDIS_CONNECTION_STRING=people-redis:6379,abortConnect=false  # Redis connection string
      - USE_URLS=http://0.0.0.0:80 # Listen on port 80

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:80"  # Exposing React app on port 3000
    networks:
      - webapp-network
    environment:
      - VITE_PEOPLE_API_URL=http://peopleapp-backend-1:5050  # Set API URL for React to interact with the backend

networks:
  webapp-network:
    driver: bridge
